services:
  # Flask
  flask:
    restart: always
    build: ./flask
    container_name: 'flask'
    tty: true
    ports:
      - '8000'
    volumes:
      - ./flask:/app
  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - '3306'
  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOSTS=${PMA_HOSTS}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    links:
      - db
    ports:
      - '${PMA_PORT}:80'
  # https-portal
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
    - flask
    restart: always
    environment:
      DOMAINS: '${DOMAIN} -> http://flask:8000'
      STAGE: '${STAGE}' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    volumes: 
      - ./ssl_certs:/var/lib/https-portal